version: 2
updates:
  - package-ecosystem: "npm" # Ή οποιοδήποτε άλλο οικοσύστημα χρησιμοποιείς
    directory: "/" # Ρίζα του repository
    schedule:
      interval: "daily" # Καθημερινός έλεγχος για ενημερώσεις
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "express"
        versions: ["4.x"]